/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Time and Number
 #	author : miyako
 #	2016/04/16
 #
 # --------------------------------------------------------------------------------*/

#include "timezone.h"
#include "smpdtfmt.h"
#include "rbnf.h"
#include "locid.h"
#include "unistr.h"

#define ISO_DATE_FORMAT_SPRINT "%4d.%2d.%2d.%2d.%2d.%2d.%3d"
#define ISO_DATE_FORMAT_STRING "yyyy.MM.dd.HH.mm.ss.SSS"
#define ISO_DATE_FORMAT_STRING_SIZE 24
#define MAX_REGION_LENGTH 4

#define NUMBER_FORMAT_SPELLOUT 0
#define NUMBER_FORMAT_ORDINAL 1
#define NUMBER_FORMAT_DURATION 2
#define NUMBER_FORMAT_NUMBERING_SYSTEM 3
#define NUMBER_FORMAT_COUNT 4
#define NUMBER_FORMAT_CUSTOM 5

// --- Time
void TIME_Get_offset(sLONG_PTR *pResult, PackagePtr pParams);
void TIME_Date_to_text(sLONG_PTR *pResult, PackagePtr pParams);
void TIME_Date_from_text(sLONG_PTR *pResult, PackagePtr pParams);
void TIME_Absolute_from_text(sLONG_PTR *pResult, PackagePtr pParams);
void TIME_Absolute_to_text(sLONG_PTR *pResult, PackagePtr pParams);
void TIME_Date_from_absolute(sLONG_PTR *pResult, PackagePtr pParams);
void TIME_Date_to_absolute(sLONG_PTR *pResult, PackagePtr pParams);

// --- Timezone
void TIMEZONE_Get_region(sLONG_PTR *pResult, PackagePtr pParams);
void TIMEZONE_Get_default(sLONG_PTR *pResult, PackagePtr pParams);
void TIMEZONE_Get_offset(sLONG_PTR *pResult, PackagePtr pParams);
void TIMEZONE_Get_display_name(sLONG_PTR *pResult, PackagePtr pParams);
void TIMEZONE_Get_GMT(sLONG_PTR *pResult, PackagePtr pParams);

// --- Number
void NUMBER_Format(sLONG_PTR *pResult, PackagePtr pParams);

// --- Information
void TIMEZONE_GET_LIST(sLONG_PTR *pResult, PackagePtr pParams);
