/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Time and Number
 #	author : miyako
 #	2013/07/31
 #
 # --------------------------------------------------------------------------------*/

#include "timezone.h"
#include "smpdtfmt.h"
#include "rbnf.h"

void _PrintUnicodeString(UnicodeString &str);
bool _TextSetUnicodeString(C_TEXT &param, UnicodeString &str);
bool _CUTF8SetUnicodeString(CUTF8String &ustr, UnicodeString &str);
