/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Time-and-Number.h
 #	source generated by 4D Plugin Wizard
 #	Project : Time and Number
 #	author : miyako
 #	2022/09/14
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_TIME_AND_NUMBER_H
#define PLUGIN_TIME_AND_NUMBER_H

#include "4DPluginAPI.h"

#include "C_BLOB.h"
#include "C_TEXT.h"
#include "C_LONGINT.h"
#include "C_TIME.h"
#include "C_DATE.h"
#include "ARRAY_TEXT.h"
#include "C_REAL.h"

#include "unicode/unistr.h"
#include "unicode/ucnv.h"
#include "unicode/utrans.h"
#include "unicode/ucsdet.h"
#include "unicode/unorm2.h"
#include "unicode/timezone.h"
#include "unicode/smpdtfmt.h"
#include "unicode/rbnf.h"
#include "unicode/locid.h"

#define ISO_DATE_FORMAT_SPRINT "%4d.%2d.%2d.%2d.%2d.%2d.%3d"
#define ISO_DATE_FORMAT_STRING "yyyy.MM.dd.HH.mm.ss.SSS"
#define ISO_DATE_FORMAT_STRING_SIZE 24
#define MAX_REGION_LENGTH 4

#define NUMBER_FORMAT_SPELLOUT 0
#define NUMBER_FORMAT_ORDINAL 1
#define NUMBER_FORMAT_DURATION 2
#define NUMBER_FORMAT_NUMBERING_SYSTEM 3
#define NUMBER_FORMAT_COUNT 4
#define NUMBER_FORMAT_CUSTOM 5

#pragma mark -

void TIME_Get_offset(PA_PluginParameters params);
void TIME_Date_to_text(PA_PluginParameters params);
void TIME_Date_from_text(PA_PluginParameters params);
void TIME_Absolute_from_text(PA_PluginParameters params);
void TIME_Absolute_to_text(PA_PluginParameters params);
void TIME_Date_from_absolute(PA_PluginParameters params);
void TIME_Date_to_absolute(PA_PluginParameters params);
void TIMEZONE_Get_region(PA_PluginParameters params);
void TIMEZONE_Get_default(PA_PluginParameters params);
void TIMEZONE_Get_offset(PA_PluginParameters params);
void TIMEZONE_Get_display_name(PA_PluginParameters params);
void TIMEZONE_Get_GMT(PA_PluginParameters params);
void NUMBER_Format(PA_PluginParameters params);
void TIMEZONE_GET_LIST(PA_PluginParameters params);

#endif /* PLUGIN_TIME_AND_NUMBER_H */
